package accountUsers;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

@RunWith(Suite.class)
@SuiteClasses({ 
		//Пользователи аккаунта 114-96 - 4431
				
	//Все ТК
	AccountUsersFirst.class,
	AccountUsersSecond.class,
	AccountUsersThird.class,
	AccountUsersFourth.class,
	AccountUsersFifth.class,
	AccountUsersSixth.class,
	AccountUsersSeventh.class,
	//AccountUsersEighth.class,   
	//AccountUsersNinth.class,   
	//AccountUsersTenth.class,   
	//AccountUsersEleventh.class,   
	//AccountUsersTwelfth.class,  
	AccountUsersThirteenth.class,	
	AccountUsersFourteenth.class,
	AccountUsersFifteenth.class,
	AccountUsersSixteenth.class,
	AccountUsersSeventeenth.class,
	//AccountUsersEighteenth.class,   
	//AccountUsersNinteenth.class,   
	//AccountUsersTwentieth.class,   
	//AccountUsersTwentyFirst.class,   
	//AccountUsersTwentySecond.class,  
	AccountUsersTwentyThird.class,
	AccountUsersTwentyFourth.class,
	//AccountUsersTwentyFifth.class,
	AccountUsersTwentySixth.class,
	//AccountUsersTwentySeventh.class,
	AccountUsersTwentyEighth.class,
	//AccountUsersTwentyNinth.class,
	AccountUsersThirtieth.class,
	//AccountUsersThirtyFirst.class,
	AccountUsersThirtySecond.class,
	AccountUsersThirtyThird.class,
	AccountUsersThirtyFourth.class,
	AccountUsersThirtyFifth.class,
	AccountUsersThirtySixth.class,
	AccountUsersThirtySeventh.class,
	AccountUsersThirtyEighth.class,
	AccountUsersThirtyNinth.class,
	AccountUsersFortieth.class,
	//AccountUsersFortyFirst.class,   
	AccountUsersFortySecond.class,
	AccountUsersFortyThird.class,
	//AccountUsersFortyFourth.class,   
	AccountUsersFortyFifth.class,
	AccountUsersFortySixth.class,
	//AccountUsersFortySeventh.class,   
	AccountUsersFortyEighth.class,
	AccountUsersFortyNinth.class,
	AccountUsersFifties.class,
	AccountUsersFiftyFirst.class,
	AccountUsersFiftySecond.class,
	AccountUsersFiftyThird.class,
	AccountUsersFiftyFourth.class,
	AccountUsersFiftyFifth.class,
	AccountUsersFiftySixth.class,
	AccountUsersFiftySeventh.class,
	//AccountUsersFiftyEighth.class,
	//AccountUsersFiftyNinth.class,
	//AccountUsersSixties.class,
	AccountUsersSixtyFirst.class,
	AccountUsersSixtySecond.class,
	AccountUsersSixtyThird.class,
	AccountUsersSixtyFourth.class,
	AccountUsersSixtyFifth.class,
	AccountUsersSixtySixth.class,
	AccountUsersSixtySeventh.class,
	AccountUsersSixtyEighth.class,
	AccountUsersSixtyNinth.class,
	AccountUsersSeventies.class,
	AccountUsersSeventyFirst.class,
	AccountUsersSeventySecond.class,
	AccountUsersSeventyThird.class,
	AccountUsersSeventyFourth.class,
	AccountUsersSeventyFourthPartTwo.class,
	AccountUsersSeventyFifth.class,
	AccountUsersSeventyFifthPartTwo.class,
	AccountUsersSeventySixth.class,
	AccountUsersSeventySeventh.class,
	AccountUsersSeventyEighth.class,
	AccountUsersSeventyEighthPartTwo.class,
	AccountUsersSeventyNinth.class,
	AccountUsersSeventyNinthPartTwo.class,
	AccountUsersEighties.class,
	AccountUsersEightyFirst.class,  
	//AccountUsersEightySecond.class,   //false
	AccountUsersEightyThird.class,
	AccountUsersEightyFourth.class,  
	//AccountUsersEightyFifth.class,  //false
	AccountUsersEightySixth.class,
	AccountUsersEightySeventh.class,   
	AccountUsersEightyEighth.class,
	AccountUsersEightyNinth.class,  
	AccountUsersNinties.class,
	AccountUsersNintyFirst.class,   //false
	AccountUsersNintySecond.class,
	AccountUsersNintyThird.class,   //false
	//AccountUsersNintyFourth.class,   //false
	//AccountUsersNintyFifth.class,  //false
	AccountUsersNintySixth.class,
	AccountUsersNintySeventh.class,
	AccountUsersNintyEighth.class,
	AccountUsersNintyNinth.class,
	AccountUsersOneHundred.class,
	AccountUsersOneHundredFirst.class,
	AccountUsersOneHundredSecond.class,
	AccountUsersOneHundredThird.class,
	AccountUsersOneHundredFourth.class,   
	AccountUsersOneHundredFifth.class,
	AccountUsersOneHundredSixth.class,
	AccountUsersOneHundredSeventh.class,
	AccountUsersOneHundredEighth.class,
	AccountUsersOneHundredNinth.class,
	AccountUsersOneHundredTenth.class, 
	//AccountUsersOneHundredEleventh.class,   
	AccountUsersOneHundredTwelfth.class,
	AccountUsersOneHundredThirteenth.class,
	AccountUsersOneHundredFourteenth.class,
	AccountUsersOneHundredFifteenth.class,
	AccountUsersOneHundredSixteenth.class,
	AccountUsersOneHundredSeventeenth.class,
	AccountUsersOneHundredEighteenth.class,
	AccountUsersOneHundredNinteenth.class,   //false
	//AccountUsersOneHundredTwenties.class,
	//AccountUsersOneHundredTwentyFirst.class,
	//AccountUsersOneHundredTwentySecond.class,  
	AccountUsersOneHundredTwentyThird.class,
	AccountUsersOneHundredTwentyThirdPartTwo.class,
	AccountUsersOneHundredTwentyFourth.class,
	AccountUsersOneHundredTwentyFourthPartTwo.class,
	
	
	/*
	//По разделам
	//Создание
	AccountUsersFirst.class,
	AccountUsersSecond.class,
	AccountUsersThird.class,
	AccountUsersFourth.class,
	AccountUsersFifth.class,
	AccountUsersSixth.class,
	AccountUsersSeventh.class,
	AccountUsersThirteenth.class,	
	AccountUsersFourteenth.class,
	AccountUsersFifteenth.class,
	AccountUsersSixteenth.class,
	AccountUsersSeventeenth.class,
	AccountUsersTwentySixth.class,
	AccountUsersTwentyEighth.class,
	AccountUsersThirtieth.class,
	AccountUsersThirtySecond.class,
	AccountUsersOneHundredSixth.class,
	AccountUsersOneHundredEighth.class,
	AccountUsersThirtyThird.class,
	AccountUsersThirtyFourth.class,
	AccountUsersSixtyFirst.class,
	AccountUsersSixtySeventh.class,
	AccountUsersSixtyEighth.class,
	AccountUsersSixtyNinth.class,
	AccountUsersSeventies.class,
	AccountUsersNinties.class,
	AccountUsersNintyThird.class,   
	AccountUsersNintySecond.class,
	AccountUsersOneHundredFourth.class,   
	AccountUsersOneHundredTenth.class, 
	AccountUsersOneHundredTwelfth.class,
	AccountUsersOneHundredThirteenth.class,
	
	//Подсказки к созданию
	//AccountUsersEighth.class,   
	//AccountUsersNinth.class,   
	//AccountUsersTenth.class,   
	//AccountUsersEleventh.class,   
	//AccountUsersTwelfth.class,  
	//AccountUsersEighteenth.class,   
	//AccountUsersNinteenth.class,   
	//AccountUsersTwentieth.class,   
	//AccountUsersTwentyFirst.class,   
	//AccountUsersTwentySecond.class,  
	AccountUsersOneHundredSeventh.class,
	AccountUsersOneHundredNinth.class,
	AccountUsersSeventyFirst.class,
	AccountUsersNintyFirst.class,   
	//AccountUsersNintyFifth.class, 
	//AccountUsersNintyFourth.class,  
	
	//Просмотр данных
	AccountUsersOneHundredNinteenth.class,
	AccountUsersTwentyThird.class,
	AccountUsersTwentyFourth.class,
	
	//Изменения настроек СМС, Активности, Роли
	AccountUsersThirtyFifth.class,
	AccountUsersThirtySixth.class,
	AccountUsersFortyEighth.class,
	AccountUsersFortyNinth.class,
	AccountUsersFifties.class,
	AccountUsersFiftyFirst.class,
	AccountUsersFiftySecond.class,
	AccountUsersFiftyThird.class,
	
	//Удаления
	AccountUsersThirtySeventh.class,
	AccountUsersThirtyEighth.class,
	//AccountUsersOneHundredEleventh.class,   
	AccountUsersOneHundredFourteenth.class,
	
	//Внесение, Изменение, Удаление
	AccountUsersFiftyFourth.class,
	AccountUsersFiftySeventh.class,
	AccountUsersFiftyFifth.class,
	AccountUsersThirtyNinth.class,
	AccountUsersFortySecond.class,
	AccountUsersFortyFifth.class,
	AccountUsersFiftySixth.class,
	AccountUsersFortieth.class,
	AccountUsersFortyThird.class,
	AccountUsersFortySixth.class,
	
	//Подсказки при удалении
	//AccountUsersFortyFirst.class,   
	//AccountUsersFortyFourth.class,   
	//AccountUsersFortySeventh.class, 
	
	//Создание Менеджеров/Пользователей с доступами
	AccountUsersSixtySecond.class,
	AccountUsersSixtyThird.class,
	AccountUsersSixtyFourth.class,
	AccountUsersSixtyFifth.class,
	AccountUsersOneHundredFifteenth.class,
	AccountUsersOneHundredSixteenth.class,
	AccountUsersOneHundredSeventeenth.class,
	AccountUsersSixtySixth.class,	
	
	//Доступы 
	AccountUsersEightySeventh.class, 
	AccountUsersEightySixth.class,
	AccountUsersEightyFirst.class, 
	AccountUsersEighties.class,
	AccountUsersSeventyThird.class,
	AccountUsersSeventySecond.class,
	AccountUsersEightyNinth.class,  
	AccountUsersEightyEighth.class,
	AccountUsersEightyFourth.class, 
	AccountUsersEightyThird.class,
	AccountUsersSeventySeventh.class,
	AccountUsersSeventySixth.class,
	
	//Сообщения к доступам
	//AccountUsersEightySecond.class,  
	AccountUsersSeventyFifth.class,
	AccountUsersSeventyFifthPartTwo.class,
	AccountUsersSeventyFourth.class,
	AccountUsersSeventyFourthPartTwo.class,
	//AccountUsersEightyFifth.class,  
	AccountUsersSeventyNinth.class,
	AccountUsersSeventyNinthPartTwo.class,
	AccountUsersSeventyEighth.class,
	AccountUsersSeventyEighthPartTwo.class,
	
	//max количество пользователей 
	AccountUsersNintySixth.class,
	AccountUsersNintySeventh.class,
	AccountUsersNintyEighth.class,
	AccountUsersNintyNinth.class,
	
	//сообщения к превышению max количества
	AccountUsersOneHundred.class,
	AccountUsersOneHundredFirst.class,
	AccountUsersOneHundredSecond.class,
	AccountUsersOneHundredThird.class,
	
	//Иное
	AccountUsersOneHundredFifth.class,
	AccountUsersOneHundredEighteenth.class,
	AccountUsersOneHundredTwentyThird.class,
	AccountUsersOneHundredTwentyThirdPartTwo.class,
	AccountUsersOneHundredTwentyFourth.class,
	AccountUsersOneHundredTwentyFourthPartTwo.class,*/
	})
public class AllTests {

}
