package rate;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

@RunWith(Suite.class)
@SuiteClasses({ 
		//Тариф - 158-149 - 6957
	
	//Все ТК
	RateFirst.class,
    RateSecond.class,
    RateThird.class,
    RateFourth.class,
    RateFifth.class,
    RateSixth.class,
    RateSeventh.class,
    RateEighth.class,
    RateNinth.class,
    RateTenth.class,
    RateEleventh.class,
    RateTwelfth.class,
    RateThirteenth.class,
    RateFourteenth.class,
    RateFifteenth.class,
    RateSixteenth.class,
    RateSeventeenth.class,
    RateEighteenth.class,
    RateNinteenth.class,
    RateTwentieth.class,
    RateTwentyFirst.class,
    RateTwentySecond.class,
    RateTwentyThird.class,
    RateTwentyFourth.class,
    RateTwentyFifth.class,
    RateTwentySixth.class,
    RateTwentySeventh.class,  
    RateTwentyEighth.class,
    RateTwentyNinth.class,
    RateThirtieth.class,
    RateThirtyFirst.class,
    RateThirtySecond.class,
    RateThirtyThird.class,
    RateThirtyFourth.class,
    RateThirtyFifth.class,
    RateThirtySixth.class,
    RateThirtySeventh.class,
    RateThirtyEighth.class,	 
    RateThirtyNinth.class, 
    RateFortieth.class,
    RateFortyFirst.class,
    RateFortySecond.class,
    RateFortyThird.class,
    RateFortyFourth.class,
    RateFortyFifth.class,
    RateFortySixth.class,
    RateFortySeventh.class,
    RateFortyEighth.class,
    RateFortyNinth.class,
	RateFifties.class,
	RateFiftyFirst.class,
	RateFiftySecond.class,
	RateFiftyThird.class,
	RateFiftyFourth.class,
	RateFiftyFifth.class,
	RateFiftySixth.class,
	RateFiftySeventh.class,
	RateFiftyEighth.class,
	RateFiftyNinth.class,
	RateSixtieth.class,
	RateSixtyFirst.class,
	RateSixtySecond.class,
	RateSixtyThird.class,
	RateSixtyFourth.class,
	RateSixtyFifth.class,
	RateSixtySixth.class,
	RateSixtySeventh.class,
	RateSixtyEighth.class,
	RateSixtyNinth.class,
	RateSeventies.class,
	RateSeventyFirst.class,
	RateSeventySecond.class,
	RateSeventyThird.class,
	RateSeventyFourth.class,
	RateSeventyFifth.class,
	RateSeventySixth.class,
	RateSeventySeventh.class,
	RateSeventyEighth.class,
	RateSeventyNinth.class,
	RateEighties.class,
	RateEightyFirst.class,
	RateEightySecond.class,
	RateEightyThird.class,
	RateEightyFourth.class,
	RateEightyFifth.class,
	RateEightySixth.class,
	RateEightySeventh.class,
	RateEightyEighth.class,
	RateEightyNinth.class,
	RateNinetieth.class,
	RateNinetyFirst.class,
	RateNinetySecond.class,
	RateNinetyThird.class,
	RateNinetyFourth.class,
	RateNinetyFifth.class,
	RateNinetySixth.class,
	RateNinetySeventh.class,
	RateNinetyEighth.class,
	RateNinetyNinth.class,
	RateOneHundred.class,
	RateOneHundredFirst.class,   //false
	RateOneHundredSecond.class,
	RateOneHundredThird.class,
	RateOneHundredFourth.class,
	RateOneHundredFifth.class,
	RateOneHundredSixth.class,
	RateOneHundredSeventh.class,   //false
	RateOneHundredEighth.class,
	RateOneHundredNinth.class,
	RateOneHundredTenth.class,
	RateOneHundredEleventh.class,
	RateOneHundredTwelfth.class,
	RateOneHundredThirteenth.class,
	RateOneHundredFourteenth.class,
	RateOneHundredFifteenth.class,
	RateOneHundredSixteenth.class,
	RateOneHundredSeventeenth.class,
	RateOneHundredEighteenth.class,
	RateOneHundredNinteenth.class,
	RateOneHundredTwenties.class,
	RateOneHundredTwentyFirst.class,
	RateOneHundredTwentySecond.class,
	RateOneHundredTwentyThird.class,
	RateOneHundredTwentyFourth.class,
	RateOneHundredTwentyFifth.class,		
	RateOneHundredTwentySixth.class,
	RateOneHundredTwentySeven.class,
	RateOneHundredTwentyEighth.class,
	RateOneHundredTwentyNinth.class,
	RateOneHundredThirtieth.class,
	RateOneHundredThirtyFirst.class,
	RateOneHundredThirtySecond.class,
	RateOneHundredThirtyThird.class,
	RateOneHundredThirtyFourth.class,
	RateOneHundredThirtyFifth.class,
	RateOneHundredThirtySixth.class,
	RateOneHundredThirtySeventh.class,
	RateOneHundredThirtyEighth.class,
	RateOneHundredThirtyNinth.class,  
	RateOneHundredFourtieth.class,
	RateOneHundredFourtyFirst.class,
	RateOneHundredFourtySecond.class,
	RateOneHundredFourtyThird.class,
	RateOneHundredFourtyFourth.class,
	RateOneHundredFourtyFifth.class,
	RateOneHundredFourtySixth.class,
	RateOneHundredFourtySeventh.class,
	RateOneHundredFourtyEighth.class,
	//RateOneHundredFourtyNinth.class,   
	//RateOneHundredFifties.class,       
	//RateOneHundredFiftyFirst.class,   
	//RateOneHundredFiftySecond.class,   
	//RateOneHundredFiftyThird.class,   
	//RateOneHundredFiftyFourth.class,   
	//RateOneHundredFiftyFifth.class,   
	//RateOneHundredFiftySixth.class,   
	RateOneHundredFiftySeventh.class,  //false
	//RateOneHundredFiftyEighth.class,  	
	
	
	/*
	//По разделам
	//Проверка общей цены
	RateFirst.class,
	RateSecond.class,
    RateThird.class,
    RateFourth.class,
    RateFifth.class,
    RateSixth.class,
    RateSeventh.class,
    RateEighth.class,
    RateNinth.class,
    RateTenth.class,
    RateEleventh.class,
    RateTwelfth.class,
    RateThirteenth.class,
    RateFourteenth.class,
    RateFifteenth.class,
    RateSixteenth.class,
    RateSeventeenth.class,
    RateEighteenth.class,
    RateNinteenth.class,
    RateTwentieth.class,
    
    //Перечень услуг
    RateTwentyFirst.class,
	RateTwentySecond.class,
	RateTwentyThird.class,
	RateTwentyFourth.class,
	
	//Изменение Тарифного плана
	RateTwentySixth.class,
	RateOneHundredFourtieth.class,
	RateOneHundredFourtyFirst.class,
	RateOneHundredFourtySecond.class,
	RateOneHundredFourtyThird.class,
	RateOneHundredFourtyFourth.class,
	RateOneHundredFourtyFifth.class,
	RateOneHundredFourtySixth.class,
	RateOneHundredFourtySeventh.class,
	RateOneHundredFourtyEighth.class,
	
	//Сообщения при изменениях и отказ
	RateTwentyFifth.class,
	RateTwentySeventh.class,  
	RateTwentyEighth.class,
	
	//Соответствие предоставляемых услуг действующего тарифного плана
	RateEightyNinth.class,
	RateNinetieth.class,
	RateNinetyFirst.class,
	RateNinetySecond.class,
	RateNinetyThird.class,
	RateNinetyFourth.class,
	RateNinetyFifth.class,
	RateNinetySixth.class,
	RateNinetySeventh.class,
	RateNinetyEighth.class,
	
	//Соответствие предоставляемых услуг при изменении
	RateTwentyNinth.class,
    RateThirtieth.class,
    RateThirtyFirst.class,
    RateThirtySecond.class,
    RateThirtyThird.class,
    RateThirtyFourth.class,
    RateThirtyFifth.class,
    RateThirtySixth.class,
    RateThirtySeventh.class,
    RateThirtyEighth.class,	    
    
    //Соответствие цены продление тарифного плана Персональный 
    RateThirtyNinth.class, 
    RateFortieth.class,
    RateFortyFirst.class,
    RateFortySecond.class,
    RateFortyThird.class,
    
    //Соответствие цены продление тарифного плана Стандартный
    RateFortyFourth.class,
    RateFortyFifth.class,
    RateFortySixth.class,
    RateFortySeventh.class,
    RateFortyEighth.class,
    RateFortyNinth.class,
	RateFifties.class,
	RateFiftyFirst.class,
	RateFiftySecond.class,
	RateFiftyThird.class,
	RateFiftyFourth.class,
	RateFiftyFifth.class,
	RateFiftySixth.class,
	RateFiftySeventh.class,
	RateFiftyEighth.class,
	
	//Соответствие цены продление тарифного плана Оптимальный
	RateFiftyNinth.class,
	RateSixtieth.class,
	RateSixtyFirst.class,
	RateSixtySecond.class,
	RateSixtyThird.class,
	RateSixtyFourth.class,
	RateSixtyFifth.class,
	RateSixtySixth.class,
	RateSixtySeventh.class,
	RateSixtyEighth.class,
	RateSixtyNinth.class,
	RateSeventies.class,
	RateSeventyFirst.class,
	RateSeventySecond.class,
	RateSeventyThird.class,
		
	//Соответствие цены продление тарифного плана Максимальный
	RateSeventyFourth.class,
	RateSeventyFifth.class,
	RateSeventySixth.class,
	RateSeventySeventh.class,
	RateSeventyEighth.class,
	RateSeventyNinth.class,
	RateEighties.class,
	RateEightyFirst.class,
	RateEightySecond.class,
	RateEightyThird.class,
	RateEightyFourth.class,
	RateEightyFifth.class,
	RateEightySixth.class,
	RateEightySeventh.class,
	RateEightyEighth.class,		
	
	//Переход с учетом превышения 
	RateNinetyNinth.class,
	RateOneHundred.class,
	RateOneHundredFirst.class,   //false
	RateOneHundredSecond.class,
	RateOneHundredThird.class,
	RateOneHundredFourth.class,
	
	//Сообщения к переходу с учетом превышения 
	RateOneHundredFifth.class,
	RateOneHundredSixth.class,
	RateOneHundredSeventh.class,   //false
	RateOneHundredEighth.class,
	RateOneHundredNinth.class,
	RateOneHundredTenth.class,
	
	//Открытие/не открытие раздела PV/UDP
	RateOneHundredEleventh.class,
	RateOneHundredTwelfth.class,
	RateOneHundredFourteenth.class,
	RateOneHundredFifteenth.class,
	RateOneHundredSixteenth.class,
	RateOneHundredSeventeenth.class,
	RateOneHundredEighteenth.class,
	RateOneHundredNinteenth.class,
	RateOneHundredTwenties.class,
	RateOneHundredTwentyFirst.class,
	RateOneHundredTwentySecond.class,
	RateOneHundredTwentyFourth.class,
	RateOneHundredTwentySixth.class,
	RateOneHundredTwentySeven.class,
	RateOneHundredTwentyEighth.class,
	RateOneHundredThirtieth.class,
	RateOneHundredThirtySecond.class,
	RateOneHundredThirtyThird.class,
	RateOneHundredThirtyFourth.class,
	RateOneHundredThirtySixth.class,
	
	//Сообщени е при открытии/не открытии раздела PV/UDP
	RateOneHundredThirteenth.class,
	RateOneHundredTwentyThird.class,
	RateOneHundredTwentyFifth.class,	
	RateOneHundredTwentyNinth.class,
	RateOneHundredThirtyFirst.class,
	RateOneHundredThirtyFifth.class,
	RateOneHundredThirtySeventh.class,
	
	//Оплата
	RateOneHundredThirtyEighth.class,
	RateOneHundredThirtyNinth.class,  
	//RateOneHundredFourtyNinth.class,   
	//RateOneHundredFifties.class,       
	//RateOneHundredFiftyFirst.class,   
	//RateOneHundredFiftySecond.class,   
	//RateOneHundredFiftyThird.class,   
	//RateOneHundredFiftyFourth.class,   
	//RateOneHundredFiftyFifth.class,   
	//RateOneHundredFiftySixth.class,   
	RateOneHundredFiftySeventh.class,  //false
	//RateOneHundredFiftyEighth.class,  	*/
	})
public class AllTests {

}
